http.host: "0.0.0.0"
#xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch.srv.gentoomaniac.net:9200"]
xpack.monitoring.enabled: false
#xpack.monitoring.elasticsearch.username: logstash_system
#xpack.monitoring.elasticsearch.password: '<logstash_system_password>'
#xpack.monitoring.elasticsearch.ssl.certificate_authority: /opt/logstash/config/certs/lets-encrypt-x3-cross-signed.pem
