---
classes:
  - docker
  - certbot
  - traefik

ressources:
  file:
    "/srv":
      ensure: directory

certbot::domain: "*.srv.gentoomaniac.net"
traefik::args:
  - --api.insecure=true
  - --entrypoints.web.address=:80
  - --entrypoints.websecure.address=:443
  - --providers.file.directory=/conf
  - --providers.file.watch=true
  - --providers.docker
  - --providers.docker.exposedbydefault=false
  - --serverstransport.insecureskipverify=true
traefik::labels: []
traefik::ports:
  - 80:80/tcp
  - 443:443/tcp
  - 8080:8080/tcp
traefik::ssl_cert_location: /srv/certbot-srv_gentoomaniac_net/data/srv.gentoomaniac.net

docker::networks:
  web:
    ensure: present

docker::volumes:
  nfs_movies:
    ensure: present
    driver: local
    options:
      type: nfs
      o: addr=10.1.1.5,nolock,soft,bg,tcp,intr,rsize=8192,wsize=8192,noatime,rw
      device: :/mnt/movies/movies
  nfs_kids_movies:
    ensure: present
    driver: local
    options:
      type: nfs
      o: addr=10.1.1.5,nolock,soft,bg,tcp,intr,rsize=8192,wsize=8192,noatime,rw
      device: :/mnt/tank0/kids_movies
  nfs_shows:
    ensure: present
    driver: local
    options:
      type: nfs
      o: addr=10.1.1.5,nolock,soft,bg,tcp,intr,rsize=8192,wsize=8192,noatime,rw
      device: :/mnt/tank3/shows
  nfs_kids_shows:
    ensure: present
    driver: local
    options:
      type: nfs
      o: addr=10.1.1.5,nolock,soft,bg,tcp,intr,rsize=8192,wsize=8192,noatime,rw
      device: :/mnt/tank0/kids_shows
  nfs_kids_shows_se:
    ensure: present
    driver: local
    options:
      type: nfs
      o: addr=10.1.1.5,nolock,soft,bg,tcp,intr,rsize=8192,wsize=8192,noatime,rw
      device: :/mnt/tank0/kids_shows_se
  nfs_sd_old:
    ensure: present
    driver: local
    options:
      type: nfs
      o: addr=10.1.1.5,nolock,soft,bg,tcp,intr,rsize=8192,wsize=8192,noatime,rw
      device: :/mnt/tank3/sd_old
  share:
    ensure: present
    driver: local
    options:
      type: nfs
      o: addr=10.1.1.5,nolock,soft,bg,tcp,intr,rsize=8192,wsize=8192,noatime,rw
      device: /mnt/tank5/share
