---
classes:
  - docker
  - certbot
  - traefik

ressources:
  file:
    "/srv":
      ensure: directory

docker::docker_users:
  - marco

certbot::domain: "*.srv.gentoomaniac.net"
traefik::args:
  - --api.insecure=true
  - --entrypoints.web.address=:80
  - --entrypoints.websecure.address=:443
  - --entrypoints.elasticsearch.address=:9200
  - --providers.file.directory=/conf
  - --providers.file.watch=true
  - --providers.docker
  - --providers.docker.exposedbydefault=false
  - --serverstransport.insecureskipverify=true
traefik::labels: []
traefik::ports:
  - 80:80/tcp
  - 443:443/tcp
  - 8080:8080/tcp
traefik::ssl_cert_location: /srv/certbot-srv_gentoomaniac_net/data/srv.gentoomaniac.net
