---
classes:
  - docker
  - certbot
  - traefik

ressources:
  file:
    "/srv":
      ensure: directory

certbot::domain: "*.srv.gentoomaniac.net"
traefik::args:
  - --api.insecure=true
  - --entrypoints.web.address=:80
  - --entrypoints.websecure.address=:443
  - --providers.file.directory=/conf
  - --providers.file.watch=true
  - --providers.docker
  - --providers.docker.exposedbydefault=false
traefik::labels:
  - "'traefik.http.routers.freenas.rule=Host(`nas.srv.gentoomaniac.net`)'"
  - "'traefik.http.routers.freenas.service=freenas'"
  - "'traefik.http.service.freenas.loadBalancer.servers.url=https://10.1.1.5:443/'"
traefik::ports:
  - 80:80/tcp
  - 443:443/tcp
  - 8080:8080/tcp
traefik::ssl_cert_location: /srv/certbot-srv_gentoomaniac_net/data/srv.gentoomaniac.net
