[http.services]
  [http.services.dummy.loadBalancer]
    [[http.services.dummy.loadBalancer.servers]]
        url = ""

  [http.services.freenas.loadBalancer]
    [[http.services.freenas.loadBalancer.servers]]
      url = "https://10.1.1.5:443/"

  [http.services.unifi.loadBalancer]
    [[http.services.unifi.loadBalancer.servers]]
      url = "https://10.1.1.2:8443/"

  [http.services.protect.loadBalancer]
    [[http.services.protect.loadBalancer.servers]]
      url = "https://10.1.1.2:7443/"

  [http.services.ck.loadBalancer]
    [[http.services.ck.loadBalancer.servers]]
      url = "https://10.1.1.2:443/"

  [http.services.proxmox1.loadBalancer]
    [[http.services.proxmox1.loadBalancer.servers]]
      url = "https://sto1-proxmox-a1.sto.gentoomaniac.net:8006/"

  [http.services.proxmox2.loadBalancer]
    [[http.services.proxmox2.loadBalancer.servers]]
      url = "https://sto1-proxmox-a2.sto.gentoomaniac.net:8006/"

[http.routers]
  [http.routers.redirect-to-https]
    rule = "hostregexp(`{host:.+}`)"
    service = "dummy"
    entryPoints = ["web"]
    middlewares = ["redirect-to-https"]

  [http.routers.freenas]
    rule = "Host(`nas.srv.gentoomaniac.net`)"
    service = "freenas"
    entryPoints = ["websecure"]
    middlewares = ["local-only-whitelist"]
    [http.routers.freenas.tls]

  [http.routers.unifi]
    rule = "Host(`unifi.srv.gentoomaniac.net`)"
    service = "unifi"
    entryPoints = ["websecure"]
    middlewares = ["local-only-whitelist"]
    [http.routers.unifi.tls]

  [http.routers.protect]
    rule = "Host(`protect.srv.gentoomaniac.net`)"
    service = "protect"
    entryPoints = ["websecure"]
    middlewares = ["local-only-whitelist"]
    [http.routers.protect.tls]

  [http.routers.ck]
    rule = "Host(`ck.srv.gentoomaniac.net`)"
    service = "ck"
    entryPoints = ["websecure"]
    middlewares = ["local-only-whitelist"]
    [http.routers.ck.tls]

  [http.routers.proxmox1]
    rule = "Host(`proxmox1.srv.gentoomaniac.net`)"
    service = "proxmox1"
    entryPoints = ["websecure"]
    middlewares = ["local-only-whitelist"]
    [http.routers.proxmox1.tls]

  [http.routers.proxmox2]
    rule = "Host(`proxmox2.srv.gentoomaniac.net`)"
    service = "proxmox2"
    entryPoints = ["websecure"]
    middlewares = ["local-only-whitelist"]
    [http.routers.proxmox2.tls]

[http.middlewares]
    [http.middlewares.redirect-to-https]
        [http.middlewares.redirect-to-https.redirectscheme]
            scheme = "https"

    [http.middlewares.local-only-whitelist]
        [http.middlewares.local-only-whitelist.ipwhitelist]
            sourcerange = ["10.1.1.0/24","10.1.15.0/24"]
